apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubeants-controller
  name: kubeants-controller
  namespace: kubeants-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeants-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubeants-controller
    spec:
      containers:
      - image: geray/kubeants-controller:v1.3.1
        imagePullPolicy: IfNotPresent
        name: kubeants-controller
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: kubeants-controller
      securityContext: {}
      terminationGracePeriodSeconds: 30