---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeants-controller
  namespace: kubeants-system
secrets:
- name: kubeants-controller-token-vfhhp
---
# ClusterRole for Controller Manager
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeants-controller
rules:
  - apiGroups: ["rbac.kubeants.io"]
    resources: ["roletemplates"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["user.kubeants.io"]
    resources: ["users"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["workspace.kubeants.io"]
    resources: ["workspaces"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["cluster.kubeants.io"]
    resources: ["clusters"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch","update"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: [ "roles","rolebindings","clusterrolebindings"]
    verbs: ["get", "list", "watch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeants-controller
subjects:
  - kind: ServiceAccount
    name: kubeants-controller
    namespace: kubeants-system  # 修改为Controller所在Namespace
roleRef:
  kind: ClusterRole
  name: kubeants-controller
  apiGroup: rbac.authorization.k8s.io