apiVersion: userbinding.kubeants.io/v1beta1
kind: UserBinding
metadata:
  name: "user1-ws1"
spec:
  user: "user1"
  scope:
    kind: "Workspace"
    name: "ws1"
  role: "admin"
# status:
#   synced: true
#   lastSyncTime: "2025-04-26T12:00:00Z"

