apiVersion: user.kubeants.io/v1beta1
kind: User
metadata:
  name: "user1"
spec:
  state: "active"
  name: "平台管理员"
  email: "user1@ka.io"
  phone: ""
  password: "Root@123"
  #clusterroles: ["admin"]  # 数组
  roles:
  - name: "admin"
    namespaces: ["test1"]
  # - name: "admin"
  #   namespaceSelector:
  #     matchLabels:
  #       kubeants.io/workspace: ws1
