apiVersion: cluster.kubeants.io/v1beta1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: kubeants-controller
    app.kubernetes.io/managed-by: kustomize
  name: cluster-sample
spec:
  # TODO(user): Add fields here
