## Append samples of your project ##
resources:
- rbac_v1beta1_roletemplate.yaml
- workspace_v1beta1_workspace.yaml
- cluster_v1beta1_cluster.yaml
- user_v1beta1_user.yaml
- userbinding_v1beta1_userbinding.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
