apiVersion: user.kubeants.io/v1beta1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: kubeants-controller
    app.kubernetes.io/managed-by: kustomize
  name: user-sample
spec:
  # TODO(user): Add fields here
