apiVersion: workspace.kubeants.io/v1beta1
kind: Workspace
metadata:
  labels:
    app.kubernetes.io/name: kubeants-controller
    app.kubernetes.io/managed-by: kustomize
  name: workspace-sample
spec:
  # TODO(user): Add fields here
